export default [
    {
        jobTitle: "Business Analyst",
        jobId: "business-analyst",
        jobDesc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!",
        jobWork: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!"
    },
    {
        jobTitle: "Customer Service",
        jobId: "customer-service",
        jobDesc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!",
        jobWork: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!"
    },
    {
        jobTitle: "Photographer",
        jobId: "photographer",
        jobDesc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!",
        jobWork: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!"
    },
    {
        jobTitle: "UI/UX Designer",
        jobId: "ui-ux-designer",
        jobDesc: "Accenture Interactive—a new breed of agency that’s all about the Experience. For us, customer experience is not an add-on; it’s foundational to who we are and how we empower our clients. As the world’s largest, most disruptive agency, we drive lasting growth for clients by helping them design, build, and run meaningful experiences that make people’s lives better, more productive, and more meaningful. We do this in three ways: by transforming organizations through standout products and services; by building and delivering award-winning campaigns so brands can engage and communicate creatively with customers at scale; and by using our top-notch skills to pilot, integrate, scale, and run the platforms that underpin the world’s greatest experiences. Visit us here to learn more about what makes us the Experience Agency. \n Digital Products - a part of Accenture Interactive - creates value for our clients, their employees, and their customers. We design and build software that changes the way people work and live. Our team is made up of 300+ employees across the US and Canada. With expertise in product strategy, project management, QA, design thinking, user-experience design/research, and impeccable development for native mobile, web, and embedded systems, we will help bring any omni-channel product vision to reality.",
        jobWork: "Design beautiful user interfaces, with a focus on digital interfaces Promote best practices in UI, UX, and interaction design Participate in strategy and brainstorm sessions with clients, to help articulate and define their goals Have a Human Centered Design approach in solving user needs with deep customer empathy Contribute wireframes, user flows, interaction prototypes, user personas, customer journeys, site maps, and other design specification materials Work closely with development teams to ensure that design specifications are implemented Collaborate effectively with remote and onsite team members, including but not limited to designers, researchers, project/product managers, QA, developers, and technical architects For now, all Accenture business travel, international and domestic, is currently restricted to client-essential sales/delivery activity only. "
    },
    {
        jobTitle: "PR and Marketing",
        jobId: "pr-and-marketing",
        jobDesc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!",
        jobWork: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum possimus ipsum, nulla tempore obcaecati id explicabo nemo expedita deserunt asperiores suscipit optio quod provident quae consequatur ipsam numquam earum vitae!"
    },
]